name: password_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  file_picker: ^6.1.1
  go_router: ^14.1.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  encrypt: ^5.0.3
  uuid: ^4.3.3
  platform_info: ^4.0.2
  intl: ^0.19.0
  hive_flutter: ^1.1.0
  talker: ^4.0.0
  talker_flutter: ^4.0.0
  talker_bloc_logger: ^4.0.0
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
      - .env
flutter_intl:
  enabled: true
